### ISSUE TITLE
VIA/Remap Support

### ISSUE THREAD

**Issue by JohnAZoidberg** [FrameworkComputer/qmk_firmware#14]
- [ ] Via Support
  - [ ] Seems all other keyboards have separate VIA variants. Why? Do we need that as well?
  - [ ] Add VIA JSON to their repo
- [ ] Remap Support
  - [ ] Add to their website
  - [x] https://github.com/remap-keys/remap/issues/751
  - [ ] https://github.com/remap-keys/remap/issues/608

**Comment by WolfIcefang** [comment]
You might want to check out Vial, an open source replica of Via https://get.vial.today/
Vial is less well known but it's a fully open source project.
Via is technically closed source, but from what little I understand it's just because the devs don't want to wade through random merge requests form internet strangers. Then again my knowledge comes entirely from a message I read in Discord last year, so take it with a grain of salt.

**Comment by nooges** [comment]
@WolfIcefang VIA used to be closed-source, but that is no longer the case, and they have recently opened up a Discord server to handle user/develop support

**Comment by WolfIcefang** [comment]
Cool! I had checked VIA's website from my phone, and the link to their GitHub was not visible from the mobile page layout.

**Comment by Blue-Sauce** [comment]
I much prefer Vial. To start with, it has more configuration options.
VIA requires a Chrome based browser to run their webapp. Vial doesn't force this. Vial has desktop apps for Windows, Linux and Mac, in addition to a web browser app. Personally, I use Firefox, I don't wish to use a Chrome based browser if I can avoid it. 
And while VIA has opened up their source, they have a history of being a pain to work with for the qmk devs. So much so that it's prompted qmk to work on a [live configuration solution, XAP](https://hackmd.io/@tzarc/ryY5liviO), that will eliminate the need for VIA. Combined VIA just doesn't seem to fit with Framework as well as Vial does.

**Comment by nyabinary** [comment]
VIAL ftw tbh

**Comment by nyabinary** [comment]
bru
